export enum NGSDivisions {
    //Storm = "Storm",
    Heroic =  "Heroic",
    Nexus = "Nexus",
    A = "A",
    // AEast = "A East",
    // AWest = "A West",
    //B = "B",
    BEast = "B East",
    BWest = "B West",
    C = "C",
    //CEast = "C East",
    //CWest = "C West",
    DEast = "D East",
    DWest = "D West",
    // D = "D",
    // EEast = "E East",
    // EWest = "E West",
    // E = "E"
}