
export enum NGSRoles {
    DivA = 'Division A',
    DivB = 'Division B',
    DivC = 'Division C',
    DivD = 'Division D',
    DivE = 'Division E',
    Nexus = 'Nexus Division',
    Heroic = 'Heroic Division',
    Storm = 'Storm Division',
    Captain = 'Captains',
    FreeAgents = 'Free Agents',
    NGSBot = 'NGSBOT',
    Muted = 'Muted',
    UnPurgeable = "UnPurgeable",
    OffRosterSub = "Off Roster Sub",
    ORSDivisionE = "ORS Div E",
    ORSDivisionD = "ORS Div D",
    ORSDivisionC = "ORS Div C",
    ORSDivisionB = "ORS Div B",
    ORSDivisionA = "ORS Div A",
    ORSDivisionHeroic = "ORS Heroic",
}