
export enum NGSRoles {
    DivA = 'Division A',
    DivB = 'Division B',
    DivC = 'Division C',
    DivD = 'Division D',
    DivE = 'Division E',
    Nexus = 'Nexus Division',
    Heroic = 'Heroic Division',
    Storm = 'Storm Division',
    Captain = 'Captains',
    FreeAgents = 'Free Agents',
    NGSBot = 'NGSBOT',
    Muted = 'Muted',
    UnPurgeable = "UnPurgeable",
    OffRosterSub = "Off Roster Sub",
    DivisionE = "ORS Div E",
    DivisionD = "ORS Div D",
    DivisionC = "ORS Div C",
    DivisionB = "ORS Div B",
    DivisionA = "ORS Div A",
    DivisionHeroic = "ORS Heroic",
}